opt_in_rules:
  - sorted_imports

disabled_rules:
  - trailing_whitespace
  - function_body_length
  - identifier_name
  - force_cast
  - line_length
  - cyclomatic_complexity

excluded:
  - Derived
  - Plugins
  - Project.swift
  - Tuist